name: greenvoice
description: "A Flutter app that empowers citizens to participate in local
  governance and community projects."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  animated_snack_bar: ^0.4.0
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.6
  eva_icons_flutter: ^3.1.0
  firebase_analytics: ^11.3.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_branch_sdk: ^8.2.0
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.3.0
  flutter_location_search:
    git:
      url: https://github.com/jeremiahseun/flutter_location_search.git
      ref: main
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_web_frame: ^1.0.0
  fluttertoast: ^8.2.8
  gap: ^3.0.1
  geolocator: ^13.0.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^3.1.2
  mapbox_maps_flutter: ^2.2.1
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  uni_links2: ^0.6.0+2
  uuid: ^4.5.1
  web: ^1.1.0


dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app-icon.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFF"
  adaptive_icon_foreground: "assets/icons/app-icon.jpg"
  web:
    generate: true
    image_path: "assets/icons/app-icon.jpg"
    background_color: "#FFFFF"
    theme_color: "#187330"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - .env
