name: greenvoice
description: "A Flutter app that empowers citizens to participate in local
  governance and community projects."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  animated_snack_bar: ^0.4.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.6
  eva_icons_flutter: ^3.1.0
  firebase_analytics: ^11.3.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_branch_sdk: ^8.2.0
  flutter_image_compress: ^2.3.0
  flutter_location_search:
    git:
      url: https://github.com/jeremiahseun/flutter_location_search.git
      ref: main
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  gap: ^3.0.1
  geolocator: ^13.0.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  isar: ^3.1.0+1
  mapbox_maps_flutter: ^2.2.1
  path_provider: ^2.1.4
  lottie: ^3.1.2
  mapbox_maps_flutter: ^2.2.1
  share_plus: ^10.0.2
  isar: ^3.1.0+1
  mapbox_maps_flutter: ^2.2.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  uni_links2: ^0.6.0+2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
