// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIitH5vbv_t4K_3e4BSAW5SopQC7_xIOE',
    appId: '1:870660907182:web:49c4bf8a8ec1c249354d3f',
    messagingSenderId: '870660907182',
    projectId: 'greenvoiceapp',
    authDomain: 'greenvoiceapp.firebaseapp.com',
    storageBucket: 'greenvoiceapp.appspot.com',
    measurementId: 'G-EB12EYD2VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAknludzskRhMbcNlsbgs4VCUxu3ja5Qvg',
    appId: '1:870660907182:android:0340cfe22f5aa962354d3f',
    messagingSenderId: '870660907182',
    projectId: 'greenvoiceapp',
    storageBucket: 'greenvoiceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7sEb26TOVXWHkXGvEzYFA-WXQsPymczQ',
    appId: '1:870660907182:ios:a645648fa7337b8e354d3f',
    messagingSenderId: '870660907182',
    projectId: 'greenvoiceapp',
    storageBucket: 'greenvoiceapp.appspot.com',
    iosBundleId: 'com.greenvoice.app',
  );

}